blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.blog_index, name='blog_index'),
    path('<int:pk>/', views.blog_detail, name='blog_detail'),
    path('<category>/', views.blog_category, name='blog_category'),
]

hello_world/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.hello_world, name='hello_world')
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import project_index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', project_index),
    path('projects/', include('projects.urls')),
    path('blog/', include('blog.urls'))
]

projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'
urlpatterns = [
    path('', views.project_index, name='project_index'),
    # path('<int:pk>', views.project_detail, name='project_detail')
]

blog/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=20)


class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField('Category', related_name='posts')


class Comment(models.Model):
    author = models.CharField(max_length=60)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

hello_world/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=20)
    image = models.FilePathField(path='/img')

blog/forms.py
from django import forms


class CommentForm(forms.Form):
    author = forms.CharField(
        max_length=60,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Comment',
            'autocomplete': 'off'
        })
    )
    body = forms.CharField(widget=forms.Textarea(
        attrs={
            'class': 'form-control',
            'placeholder': 'Leave a comment',
            'autocomplete': 'off'
        }
    ))

blog/views.py
from django.shortcuts import render

from blog.forms import CommentForm
from blog.models import Comment, Post


def blog_index(request):
    posts = Post.objects.all().order_by('-created_on')
    return render(request, 'blog_index.html', {'posts': posts})


def blog_category(request, category):
    posts = Post.objects.filter(
        categories__name__contains=category
    ).order_by('-created_on')

    context = {
        'posts': posts,
        'category': category
    }

    return render(request, 'blog_category.html', context)


def blog_detail(request, pk):
    post = Post.objects.get(pk=pk)

    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(
                author=form.cleaned_data['author'],
                body=form.cleaned_data['body'],
                post=post
            )
            comment.save()

    comments = Comment.objects.filter(post=post).order_by('-created_on')[:5]
    context = {
        'post': post,
        'comments': comments,
        'form': form,
        'comments_count': comments.count()
    }

    return render(request, 'blog_detail.html', context)

hello_world/views.py
from django.shortcuts import render


def hello_world(request):
    return render(request, 'index.html', {})

personal_portfolio/views.py
from django.shortcuts import render


def project_index(request):
    return render(request, 'project_index.html')

projects/views.py
from django.shortcuts import render

from projects.models import Project


def project_index(request):
    projects = Project.objects.all()
    return render(request, 'project_index.html', {'projects': projects})


# def project_detail(request, pk):
#     project = Project.objects.get(pk=pk)
#     return render(request, 'detail.html', {'project': project})

blog/templates/blog_category.html
{% extends "base.html" %}

{% block page_content %}
    <h1>Post Categories</h1>
    
{% endblock %}

blog/templates/blog_detail.html
{% extends "base.html" %}
{% block page_content %}
    <div class="col-md-8 offset-md-2">
        <h1>{{ post.title }}</h1>
        <small>
            {{ post.created_on.date }} |&nbsp;
            Categories:&nbsp;
            {% for category in post.categories.all %}
                <a href="{% url 'blog:blog_category' category.name %}">{{ category.name }}</a>
            {% endfor %}
        </small>
        <p>{{ post.body | linebreaks }}</p>
        <h3>Leave a comment:</h3>
        <form action="{% url 'blog:blog_detail' post.pk %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ form.author }}
                {{ forms.author.errors }}
            </div>
            {{ form.author.errors }}
            <div class="form-group">
                {{ form.body }}
            </div>
            {{ forms.body.errors }}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        <br>
        {% if comments %}
            <h3>
                <b>{{ comments_count }}</b>&nbsp;
                Comment{% if comments_count > 1 %}s{% endif %}
                {{ value|yesno:'s,' }}
            </h3>
        {% endif %}
        {% for comment in comments %}
            <p>
                On {{ comment.created_on.date }}&nbsp;;
                <b>{{ comment.author }}</b> wrote:
            </p>
            <p>{{ comment.body }}</p>
        {% endfor %}
    </div>
{% endblock %}

blog/templates/blog_index.html
{% extends "base.html" %}

{% block page_content %}
    <div class="col-md-8 offset-md-2">
        <h1>Blog Index</h1>
        <hr>
        {% for post in posts %}
            <h2>
                <a href="{% url 'blog:blog_detail' post.pk %}">{{ post.title }}</a>
            </h2>
            <small>
                {{ post.created_on.date }} |&nbsp;
                Categories:&nbsp;
                {% for category in post.categories.all %}
                    <a href="{% url 'blog:blog_category' category.name %}">{{ category.name }}</a>
                {% endfor %}
            </small>
            <p>{{ post.body | slice:":400" }}...</p>
        {% endfor %}
    </div>
{% endblock %}

hello_world/templates/index.html
{% extends "base.html" %}

{% block page_content %}
    <h1>Hello world</h1>
{% endblock %}

personal_portfolio/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/">RP Portfolio</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home</a>
                </li>
                {% comment %}<li class="nav-item">
                    <a href="{% url 'projects:project_index' %}" class="nav-link">Projects</a>
                </li>{% endcomment %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:blog_index' %}">Blog</a>
                </li>
            </ul>
        </div>
    </div>

</nav>
<div class="container">
    {% block page_content %}{% endblock %}
</div>
<script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

personal_portfolio/templates/project_index.html
{% extends "base.html" %}

{% block page_content %}
    <div class="col-md-8 offset-md-2">
        <h1 class="text-center">Hello world, <br> <small>Check out my site</small></h1>
    </div>
{% endblock %}

projects/templates/detail.html
{% extends "base.html" %}
{% load static %}

{% block page_content %}
    <h1>{{ project.title }}</h1>
    <div class="row">
        <div class="col-md-8">
            <img src="{% static project.image %}" alt="" width="100%">
        </div>
        <div class="col-md-4">
            <h5>About the project:</h5>
            <p>{{ project.description }}</p>
            <br>
            <h5>Technology used:</h5>
            <p>{{ project.technology }}</p>
        </div>
    </div>
{% endblock %}

projects/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block page_content %}

    <h1>Projects</h1>

    <div class="row">

        {% for project in projects %}

            <div class="col-md-4">

                <div class="card mb-2">

                    <img class="card-img-top" src="{% static project.image %}">

                    <div class="card-body">

                        <h5 class="card-title">{{ project.title }}</h5>

                        <p class="card-text">{{ project.description }}</p>

                        <a href="{% url 'project_detail' project.pk %}"

                           class="btn btn-primary">

                            Read More

                        </a>

                    </div>

                </div>

            </div>

        {% endfor %}

    </div>

{% endblock %}

projects/templates/project_index.html
{% extends "base.html" %}
{% load static %}

{% block page_content %}

    <h1>Projects</h1>

    <div class="row">

        {% for project in projects %}

            <div class="col-md-4">

                <div class="card mb-2">

                    <img class="card-img-top" src="{% static project.image %}">

                    <div class="card-body">

                        <h5 class="card-title">{{ project.title }}</h5>

                        <p class="card-text">{{ project.description }}</p>

                        <a href="{% url 'project_detail' project.pk %}"

                           class="btn btn-primary">

                            Read More

                        </a>

                    </div>

                </div>

            </div>

        {% endfor %}

    </div>

{% endblock %}